id: dbmarlin
displayName: DBmarlin
description: |
  DBmarlin monitors database performance, tracks changes and helps your databases run fast. 
icon: logo.svg
install:
  primary:
    nerdlet:
      nerdletId: nr1-install-newrelic.quickstart-installation-plan
      nerdletState:
        quickstartId: a0daa1f8-99de-41ba-b7cb-7dd87c1bf7f2
      requiresAccount: true
  fallback:
    link:
      url: https://docs.dbmarlin.com/docs/integrations/newrelic
keywords:
  - database
  - performance
  - cockroach
  - db2
  - mysql
  - maria
  - oracle
  - postgres
  - sql
  - newrelic partner
categoryTerms:
  - infrastructure
  - newrelic partner
