# Sets the URL name of the quickstart on public I/O (required)
slug: blazor

# Displayed in the UI (required)
title: Blazor

# Long-form description of the quickstart (required)
description: |
  The Blazor quickstart allows you to get visibility into the performance of your Blazor application.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Get an actionable look at your Blazor applications performance in seconds with the Blazor quickstart for New Relic.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Jack de la Motte
  - Cesar Pichardo
  - Michelle Yi
  - Dabel Obikili
  - Bria Brewton
  - Yasir Basit

# Keywords for filtering / searching criteria in the UI
keywords:
  - Blazor
  - .NET
  - .NET Core
  - C#

alerts:
  - High CPU Usage
  - High Error Rate
dashboards:
  - Blazor
# Documentation references
documentation:
  - name: Blazor Docs
    url: https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor
    description: Intro to the Blazor framework for .NET

# Content / Design
icon: logo.svg
website: https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor
